#"properties to yaml" google // use https://env.simplestep.ca/

server:
  port: 8082
spring:
  profiles:
    active: dev

---
# dev config
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: 'jdbc:mysql://localhost:3306/project2024'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: 'Welcome, Mr. Krabs! This is dev environment!'

#Exposing all of the endpoints of actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

# prod config
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: 'jdbc:mysql://localhost:3306/project2024_prod'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: 'Welcome, Mr. Krabs! This is prod environment!'
